// <auto-generated />
using EmployeeManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210427095909_AddPhotoPath")]
    partial class AddPhotoPath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photopath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("statelist")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 1,
                            Email = "dayo@techspace.com.ng",
                            Gender = 0,
                            Name = "Dayo",
                            Phone = "08067013148",
                            statelist = 4
                        },
                        new
                        {
                            Id = 2,
                            Department = 1,
                            Email = "john@techspace.com.ng",
                            Gender = 0,
                            Name = "John",
                            Phone = "08067013148",
                            statelist = 0
                        },
                        new
                        {
                            Id = 3,
                            Department = 2,
                            Email = "mary@techspace.com.ng",
                            Gender = 1,
                            Name = "Mary",
                            Phone = "08067013148",
                            statelist = 3
                        },
                        new
                        {
                            Id = 4,
                            Department = 4,
                            Email = "abiodun@techspace.com.ng",
                            Gender = 0,
                            Name = "Abiodun",
                            Phone = "08067013148",
                            statelist = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
